### ISSUE TITLE
Recommend number of containers

### ISSUE THREAD

**Issue by cchristelis** [HaitiData/haitidata#10]
# Problem

Since the load on the server is likely to be relatively stable, we need to pre-specify a recommended number of containers per component.

# Proposed Solution

Set the number of containers in the rancher configuration.

**Comment by cchristelis** [comment]
Set containers to autostart on the server.

**Comment by cchristelis** [comment]
@euclidian please have a look at this.

**Comment by euclidian** [comment]
@cchristelis can you give me with possible server spesification?

**Comment by cchristelis** [comment]
@euclidian, @dimasciput should has deployed to the server before.

**Comment by euclidian** [comment]
I'm testing with 300 simultaneous users for POST and GET using Locust

![image](https://user-images.githubusercontent.com/2271663/29857807-afd3f19e-8d84-11e7-8aac-40dd93913be8.png)

I think it is still possible if we start with 10 containers at first. Because we have 12 core x 3.9GHz and lots of RAM (65 GB)

**Comment by cchristelis** [comment]
We'll start with 3 and adjust according to demand.
