### ISSUE TITLE
Update Layer style

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#126]
There is a crash when the user tries to update the layer style for this layer:

http://haitidata.dev.ithacaweb.org/gs/geonode:hti_boundaries_departements_adm1_cnigs_polygon/style/manage

When the use clicks on "Update Available Styles" the result is this:

![image](https://user-images.githubusercontent.com/16922193/32279116-22522f98-beee-11e7-9e60-18d7e8084115.png)

**Comment by AndreaAjmar** [comment]
The issue is not affecting the production site. Verified on the following layers:
http://haitidata.org/layers/geonode:hti_boundaries_departements_adm1_cnigs_polygon
http://haitidata.org/layers/geonode:hti_boundaries_communes_adm2_cnigs_polygon
http://haitidata.org/layers/geonode:gis_osm_water_a_free_1

As the development site will be re-configured from scratch, this issue can be considered closed.
