### ISSUE TITLE
I can not view some layers as public user

### ISSUE THREAD

**Issue by edejude** [HaitiData/haitidata#134]
I uploaded some layers on Haitidata with the user PRCU, i can not view some when i am connected as PRCU user, neither as not connected user. But, when i am connected as superadmin(cnigs), i can view them.

![image](https://user-images.githubusercontent.com/3659579/32444260-f2f4c496-c2cf-11e7-84d2-0cb57faaf13e.png)

**Comment by gmtoglia** [comment]
I want to add that when the user tries to download the layer (as image, csv, shapefile, etc.) the system returns this:

![image](https://user-images.githubusercontent.com/16922193/32454520-747b7588-c2ed-11e7-8009-8372319a66a6.png)

**Comment by ppasq** [comment]
This seems a GeoFence issue. Need to investigate further.

**Comment by gmtoglia** [comment]
If we add a layer through the import CSV feature, there is no issue. If we upload an SHP we have the issue.

**Comment by ppasq** [comment]
According to the GeoFence developers this is a version 2.9 bug. We are evaluating whether to upgrade or try fix the current version.

**Comment by sbsimo** [comment]
Hello everybody,
this issue seems to be solved here https://github.com/GeoNode/geonode/pull/3470

I tested it locally on a VM and the GeoFence rules are applied correctly.
I would suggest to:
1. install the fixed version of the GeoNode/python components: https://github.com/GeoNode/geonode/tree/2.6.x
2. insert the setting 'GEOFENCE_SECURITY_ENABLED' : True in the local_settings.py file

A pull request will follow soon.

**Comment by dimasciput** [comment]
Fixed in https://github.com/sbsimo/haitidata/commit/78ef22b926663e5296d4e1d6dc14640fa4c22e48
