### ISSUE TITLE
Template issue on Ortho page

### ISSUE THREAD

**Issue by cchristelis** [HaitiData/haitidata#142]
# Problem

Currently, we have the wrong text on the ortho image pages. This means the text and translations are incorrect.

# Proposed Solution

Update the template.

**Comment by ppasq** [comment]
The template content is based on the layer name. Since the ortho images layer name was changed in production from ortho_images to ortho_images_pyramid the template is not working anymore.
This line must be edited: https://github.com/HaitiData/haitidata/blob/development/django_project/core/templates/clip-and-ship/clip-page.html#L22

**Comment by dimasciput** [comment]
Updated - http://haitidata.org/clip/ortho_images_pyramid
