### ISSUE TITLE
Boundaries data don't apperar when you're not super-admin and problem to download

### ISSUE THREAD

**Issue by edejude** [HaitiData/haitidata#161]
Hello everyone, 
I got some issues with boundarries data, they do not appear when user is not connected or user is not super admin. The menu for downloading the layer is deplicated 3 times when user wants to downlaod layer.
Specially with the layer: Hti Boundaries Sections Communales Adm3 Cnigs Polygon

![image](https://user-images.githubusercontent.com/3659579/35452402-5dddf4cc-0294-11e8-8e34-ca1c4ad509a0.png)

**Comment by sbsimo** [comment]
Hello @edejude ,
is this related to the mentioned layer only? 
We are going to start working on it.

**Comment by sbsimo** [comment]
@edejude with respect to the download links, this is due to the fact that several links with the same name are contained in the Links table of HaitiData.org (see http://haitidata.org/admin/base/link/?resource__id__exact=16)

I'm not aware about the cause that brought to this situation, nevertheless it can be corrected by deleting the wrong/non-used links. I'm going to do it for the mentioned layer.

**Comment by edejude** [comment]
Hello @sbsimo ,
Thank you to work on this issue. Sorry, i was not available to reply. The  issue is related to these following layers as well:
Hti Boundaries Departements Adm1 Cnigs Line
Hti Boundaries Communes Adm2 Cnigs Polygon
Hti Boundaries Departements Adm1 Cnigs Polygon
Hti Boundaries Sections Communales Adm3 Cnigs Line

**Comment by sbsimo** [comment]
Hello @edejude ,
true, the layers you listed had the same issues indeed.
I fixed all of them, now they should work as expected.

**Comment by edejude** [comment]
Thank you @sbsimo .
