### ISSUE TITLE
Authentication issue between GeoNode, GeoServer and DB

### ISSUE THREAD

**Issue by ppasq** [HaitiData/haitidata#19]
On the development branch a vanilla GeoServer (2.9.1) is downloaded. Should be a custom 2.10-snapshot. Please see: https://github.com/GeoNode/geonode/blob/master/dev_config.yml#L2-L3

**Comment by meomancer** [comment]
hi @ppasq 
because we are using docker, our geoserver is downloaded from docker hub
https://hub.docker.com/r/kartoza/geoserver/

which are using 2.9.1:
https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile#L19

we could ask tim to release docker-geoserver that uses 2.10
or
we could update makefile in our local (not use dockerhub)

what do you think @cchristelis ?

**Comment by ppasq** [comment]
hi @meomancer 
the GeoServer is now correct but I'm still having the authentication issue. Same as you?

**Comment by cchristelis** [comment]
@ppasq and @meomancer, this is definately a settings issue. I think it is the fact that we are trying to do this over http. I have temporarily disabled this and it is working, but this is not the best solution.
